%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Sacha\OneDrive - UCL\EPL\Master\Q9\LSINF2345\PROJECT\Project-Git\LSINF2345\graph2.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2020/12/02 18:38:40

%% Initialize variables.
clear
close
filename = 'C:\Users\Sacha\OneDrive - UCL\EPL\Master\Q9\LSINF2345\PROJECT\Project-Git\LSINF2345\graph2.txt';
delimiter = {',',' ','[',']'};

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'EmptyValue', NaN,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
graph2 = [dataArray{1:end-1}];
%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;
%% Plot graph
% cycle 0
G = digraph(1, 2);
for i = 2:51
    G = addedge(G,graph2(i,1), graph2(i,[2,3]));
end
figure
plot(G);

% cycle 20
length_vector = 8 - sum(isnan(graph2(52,:)));
G2 = digraph(graph2(52,1), graph2(52,[2:length_vector]));
for i = 53:127
    length_vector = 8 - sum(isnan(graph2(i,:)));
    G2 = addedge(G2,graph2(i,1), graph2(i,[2:length_vector]));
end 
figure
plot(G2)

% cycle 20
length_vector = 8 - sum(isnan(graph2(52,:)));
G2 = digraph(graph2(52,1), graph2(52,[2:length_vector]));
for i = 53:127
    length_vector = 8 - sum(isnan(graph2(i,:)));
    G2 = addedge(G2,graph2(i,1), graph2(i,[2:length_vector]));
end 
figure
plot(G2)










